apiVersion: v1
kind: Pod
metadata:
  name: limit-test
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "110m"
      command: ["stress"]
      args: ["--cpu", "2"]