apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi