apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:purple
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: A_SUPER_SECRET_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: kuard
                  key: token
          command:
            - "/kuard"
            - "$(A_SUPER_SECRET_TOKEN)"
