name: Markdown to PDF

on:
  push:
  schedule:
    - cron: "* 2 * * *"

jobs:
  converttopdf:
    name: Build PDF

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - uses: xt0rted/markdownlint-problem-matcher@v1

      - name: Lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: .markdownlint.json

      - name: Merge Files
        run: |
          mkdir input

          for file in manuscript/*.md; do
            cat "$file";
          done > input/kubernetes-guide.md

      - name: Generate PDF
        uses: baileyjm02/markdown-to-pdf@master
        with:
          input_dir: input
          output_dir: output
          images_dir: manuscript/resources/images
          image_import: resources/images
          build_html: false

      - name: Upload Artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: Kubernetes Guide
          path: output/kubernetes-guide.pdf

      - name: Set Variables
        id: vars
        if: github.ref == 'refs/heads/master' && github.event_name == 'schedule'
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - name: Create Release
        id: create_release
        if: github.ref == 'refs/heads/master' && github.event_name == 'schedule'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.today }}
          release_name: Build ${{ steps.vars.outputs.today }}
          body: ~
          draft: false
          prerelease: true

      - name: Upload Release Asset
        if: github.ref == 'refs/heads/master' && github.event_name == 'schedule'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/kubernetes-guide.pdf
          asset_name: kubernetes-guide-${{ steps.vars.outputs.today }}.pdf
          asset_content_type: application/pdf
